export enum GRAPH_STATE_ACTIONS {
  SET_GRAPH = "SET_GRAPH",
  UPDATE_NODE_DATA = "UPDATE_NODE_DATA",
  POPULATE_FORM_FROM_ANCESTORS = "POPULATE_FORM_FROM_ANCESTORS",
  REMOVE_INHERITED_FIELDS = "REMOVE_INHERITED_FIELDS",
}
